# Default values to deploy a virtual machine instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

containerDisk:
  repository: "quay.io/kubevirt"
  name: "cirros-container-disk-demo"
  tag: latest

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 1
    memory: 64Mi
